version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:5000"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root



